[[plugins]]
package = "@netlify/plugin-nextjs"

  [plugins.inputs]
  nextConfig = """
    module.exports = {
      experimental: {
        optimizeCss: true
      },
      messages: {
        webpack5: false,
        noCache: false
      }
    }
  """
[build.environment]
NPM_CONFIG_PRODUCTION = "false"